import type { City, EventItem } from './types';

// Supabase env nélkül (DEMÓ mód) ebből dolgozik a felület, így a UI
// backend nélkül is kipróbálható. Szeged-fókusz: a demó adatok is a
// körzetből valók.

export const DEMO_CITIES: City[] = [
  { name: 'Algyő', latitude: 46.3319, longitude: 20.2072 },
  { name: 'Csongrád', latitude: 46.7084, longitude: 20.1434 },
  { name: 'Hódmezővásárhely', latitude: 46.4181, longitude: 20.33 },
  { name: 'Kistelek', latitude: 46.4736, longitude: 19.98 },
  { name: 'Makó', latitude: 46.2219, longitude: 20.4809 },
  { name: 'Mórahalom', latitude: 46.2181, longitude: 19.8844 },
  { name: 'Ópusztaszer', latitude: 46.4889, longitude: 20.0817 },
  { name: 'Sándorfalva', latitude: 46.3619, longitude: 20.1044 },
  { name: 'Szeged', latitude: 46.253, longitude: 20.1414 },
  { name: 'Szentes', latitude: 46.654, longitude: 20.2648 },
];

export const DEMO_EVENTS: EventItem[] = [
  {
    id: 'demo-1',
    title: 'Azahriah — Nyáresti Koncert',
    categories: ['konnyuzene'],
    city: 'Szeged',
    venue: 'Szegedi Szabadtéri Játékok',
    latitude: 46.2489,
    longitude: 20.1492,
    start_time: '2026-07-24T20:00:00+02:00',
    end_time: '2026-07-24T23:00:00+02:00',
    description:
      'A magyar pop üstököse hatalmas nyáresti show-val érkezik a Dóm térre — vendégekkel és új dalokkal.',
    source_url: 'https://www.szegediszabadteri.hu/',
    image_url: null,
  },
  {
    id: 'demo-2',
    title: 'Fény és Forma — Modern Art Kiállítás',
    categories: ['kiallitas'],
    city: 'Szeged',
    venue: 'REÖK Palota',
    latitude: 46.2521,
    longitude: 20.1441,
    start_time: '2026-07-18T10:00:00+02:00',
    end_time: '2026-08-30T18:00:00+02:00',
    description:
      'Kortárs magyar képzőművészek fényinstallációi és szoborkísérletei a szecessziós palota termeiben.',
    source_url: 'https://www.reok.hu/',
    image_url: null,
  },
  {
    id: 'demo-3',
    title: 'Gryllus Vilmos: Maszkabál',
    categories: ['konnyuzene', 'csaladi'],
    city: 'Szeged',
    venue: 'Szent-Györgyi Albert Agóra',
    latitude: 46.2483,
    longitude: 20.1447,
    start_time: '2026-07-26T10:30:00+02:00',
    end_time: null,
    description:
      'A kicsik kedvenc dalai élőben — közös éneklés, tánc és persze maszkabál a koncert végén.',
    source_url: 'https://agoraszeged.hu/',
    image_url: null,
  },
  {
    id: 'demo-4',
    title: 'Szimfonikus Nyáresti Hangverseny',
    categories: ['hangverseny'],
    city: 'Szeged',
    venue: 'Szegedi Nemzeti Színház',
    latitude: 46.2529,
    longitude: 20.1439,
    start_time: '2026-07-31T19:00:00+02:00',
    end_time: null,
    description:
      'A Szegedi Szimfonikus Zenekar évadzáró estje Beethoven- és Kodály-művekkel.',
    source_url: 'https://szinhaz.szeged.hu/',
    image_url: null,
  },
  {
    id: 'demo-5',
    title: 'Dumaszínház: Nyári Best Of',
    categories: ['standup'],
    city: 'Szeged',
    venue: 'IH Rendezvényközpont',
    latitude: 46.2494,
    longitude: 20.1518,
    start_time: '2026-08-05T19:30:00+02:00',
    end_time: null,
    description:
      'A Dumaszínház kedvenc előadói egy színpadon: válogatás az évad legütősebb poénjaiból.',
    source_url: 'https://dumaszinhaz.hu/',
    image_url: null,
  },
  {
    id: 'demo-6',
    title: 'Családi Nap az Emlékparkban',
    categories: ['csaladi'],
    city: 'Ópusztaszer',
    venue: 'Ópusztaszeri Nemzeti Történeti Emlékpark',
    latitude: 46.4889,
    longitude: 20.0817,
    start_time: '2026-07-19T10:00:00+02:00',
    end_time: '2026-07-19T18:00:00+02:00',
    description:
      'Kézműves foglalkozások, íjászat, jurtafalu és lovasbemutató egész nap.',
    source_url: 'https://opusztaszer.hu/',
    image_url: null,
  },
  {
    id: 'demo-7',
    title: 'Szegedi Éjszakai Futás',
    categories: ['sport'],
    city: 'Szeged',
    venue: 'Széchenyi tér',
    latitude: 46.2536,
    longitude: 20.1461,
    start_time: '2026-08-08T20:00:00+02:00',
    end_time: null,
    description:
      'Öt és tíz kilométeres éjszakai futam a Tisza-parti fények között — rajtcsomaggal és éremmel.',
    source_url: 'https://szegedtourism.hu/',
    image_url: null,
  },
  {
    id: 'demo-8',
    title: 'JATE Klub — Retro Party',
    categories: ['buli'],
    city: 'Szeged',
    venue: 'JATE Klub',
    latitude: 46.2461,
    longitude: 20.1432,
    start_time: '2026-08-02T22:00:00+02:00',
    end_time: null,
    description:
      'A 90-es és 2000-es évek legnagyobb slágerei hajnalig — az egyetemi klub klasszikus retro estje.',
    source_url: 'https://www.jateklub.hu/',
    image_url: null,
  },
];
